@baseUrl = http://localhost:8080

### Health check Vote API

GET {{baseUrl}}/health HTTP/1.1

### Send a vote to be processed

POST {{baseUrl}}/api/v1/votes HTTP/1.1
Content-Type: application/json

{
    "pollId": 1,
    "alternativeId": 1,
    "username": "Dave Grohl"
}
